### ISSUE TITLE
null和“”问题

### ISSUE THREAD

**Issue by sannere** [sannere/lintcode#3]
有一道题，比较两个字符串的，我有进行判断字符串是否isEmpty(),但是有一个测试结果，说如果是null的话我的代码不通过。。。
但是如果我改成判断字符串是否为空时，编译告诉我：
![image](https://user-images.githubusercontent.com/35032210/43675516-48fe6c38-9814-11e8-85fe-2063739d7f8c.png)
哭哭  @windmemory

**Comment by sannere** [comment]
知道问题所在啦，😝

**Comment by windmemory** [comment]
嗯嗯~ 那把这个issue关了哦~
