### ISSUE TITLE
关于continue

### ISSUE THREAD

**Issue by sannere** [sannere/lintcode#5]
那天看令狐冲视频的时候，他写代码有个奇怪的地方：
在for循环里，加了一个判断条件：
```java
if (i < m) {
continue;}

if (i > m) {
....}
```
第一个判断不是很多余吗，还是说这是一种方便阅读的编程逻辑，应该被鼓励的？
 @windmemory

**Comment by windmemory** [comment]
`continue` 会跳过`for`循环里面的内容，直接进入到下一个，所以不多余的~
