### ISSUE TITLE
关于intelliJ工程

### ISSUE THREAD

**Issue by sannere** [sannere/lintcode#6]
#### 想开一个新的test工程：
只用来测试简单的几行代码，所以想即写即编译，越简单越好。主要是有的时候有关于java的语法不确定的地方，想写几行简单的代码做测试。但是现在我每写一道题，都需要在一个包含
``` java
public static void main(String[] args) 
```
的文件中先调用我的解题的文件，才可以编译，过程比较麻烦。

> 要求：不需要调用现在的Solution中那个main() 所在的文件，操作越简单越好。

现在我直接写一个文件，存在文件家里，一编译系统还是跑原来那个Solution文件，哪怕原本都没打开Solution也不行。
所以，是说一个工程里只能有一个带main的文件，所以如果我想领写一个test文件，就必须另建一个工程吗？
还是在这个工程里也可以，需要做哪些修改或者设置？

![image](https://user-images.githubusercontent.com/35032210/43990579-91a0454e-9d8f-11e8-890a-8b8d204042d8.png)

@windmemory

**Comment by windmemory** [comment]
我过去帮你处理一下吧
